name: automerge
on:
  pull_request:
    types:
      - opened
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # Gives time for the automerge label to be added to the PR
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: "DEBUG"
          MERGE_DELETE_BRANCH: "true"
