name: automerge
on:
  # pull_request:
  #   types:
  #     - opened
  check_suite:
    types:
      - completed
    branches: new-submission-form
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
